name: Deploy Frontend to Cloud Run

on:
  push:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/deploy-frontend.yml"
      - "client/Dockerfile"
      - "client/package.json"
      - "client/package-lock.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Docker
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rdscampervan/frontend:${{ github.sha }}
          docker build -t $IMAGE_TAG ./client
          docker push $IMAGE_TAG

      - name: Deploy to Cloud Run
        run: |
          IMAGE_TAG=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rdscampervan/frontend:${{ github.sha }}
          gcloud run deploy rdscampervan-frontend \
            --image=$IMAGE_TAG \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --port=80 \
            --memory=512Mi
