name: Deploy Frontend to Cloud Run


on:
  push:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/deploy-frontend.yml"
      - "client/Dockerfile"
      - "client/package.json"
      - "client/yarn.lock"

jobs:
  
  deploy:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Docker with Google Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rdscampervans/frontend:${{ github.sha }}
          docker build -t $IMAGE_TAG ./client

      - name: Push Docker image to Artifact Registry
        run: |
          IMAGE_TAG=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rdscampervans/frontend:${{ github.sha }}
          docker push $IMAGE_TAG

      - name: Deploy to Cloud Run
        run: |
          IMAGE_TAG=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rdscampervans/frontend:${{ github.sha }}
          gcloud run deploy rdscampervan-frontend \
            --image=$IMAGE_TAG \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --port=80 \
            --memory=512Mi
 